version: '3.5'
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api_gateway
    environment:
      - NODE_ENV=development
      - PORT=3001
      - POKEDEX_MS_HOST=pokedex_api
    ports:
      - 3001:3001
      - 9228:9229
    volumes:
      - "/app/node_modules"
      - "./:/app"
    command: npm run start:debug
    networks:
      - api-gateway-network
networks:
  api-gateway-network:
    name: apiGatewayNetwork
    driver: bridge
  