version: '3.5'
services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_ENV=development
    container_name: api_gateway
    entrypoint: /app/builds/entrypoints/entrypoint-dev.sh
    environment:
      PORT: 3001
      POKEDEX_MS_HOST: ${POKEDEX_MS_HOST}
    ports:
      - 3001:3001
      - 9228:9229
    volumes:
      - "./:/app"
    networks:
      - api-gateway-network
networks:
  api-gateway-network:
    name: apiGatewayNetwork
    driver: bridge
