/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace pokedex {
    // HealthCheck Module
    export interface HealthService {
        check(
            data: google.protobuf.Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<HealthCheckDto>;
    }
    export interface HealthCheckDto {
        message?: string;
    }
    // Nature Module
    export interface NatureService {
        getNatures(
            data: google.protobuf.Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ResponseNatureDto>;
    }
    export interface ResponseNatureDto {
        data?: pokedex.NatureDto[];
    }
    export interface NatureDto {
        id?: number;
        name?: string;
        increase?: google.protobuf.StringValue;
        decrease?: string;
    }
}
export namespace google {
    export namespace protobuf {
        // tslint:disable-next-line:no-empty-interface
        export interface Empty {
        }
        export interface DoubleValue {
            value?: number;
        }
        export interface FloatValue {
            value?: number;
        }
        export interface Int64Value {
            value?: number;
        }
        export interface UInt64Value {
            value?: number;
        }
        export interface Int32Value {
            value?: number;
        }
        export interface UInt32Value {
            value?: number;
        }
        export interface BoolValue {
            value?: boolean;
        }
        export interface StringValue {
            value?: string;
        }
        export interface BytesValue {
            value?: Uint8Array;
        }
    }
}

